---
title: "Gov 2213"
author: "Sophia Freuden"
date: "4/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(lubridate)
library(readxl)
library(scales)
library(tidyverse)
```

```{r}
google <- read_xlsx("google.xlsx")
```

```{r}
graph1 <- google %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = sorosWW, color = "'Soros' Worldwide")) +
  geom_line(aes(y = sorosCyrWW, color = "Soros (Cyr.) Worldwide")) +
  geom_line(aes(y = sorosHU, color = "'Soros' Hungary")) +
  geom_line(aes(y = sorosUS, color = "'Soros' US")) +
  labs(title = "Google Trends for 'Soros' Search Terms Over Time",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.",
       y = "Relative Search Frequency",
       x = "Time",
       color = "Search Term")
```

```{r}
pdf("graph1.pdf", width = 10, height = 4)
graph1
dev.off()
```

```{r}
stats <- read_xlsx("stats.xlsx") %>%
  mutate(gdpPerCap = GDP/Population)
```

```{r}
graph2 <- stats %>% ggplot(aes(x = Year, y = GDP)) +
  geom_line() +
  labs(title = "GDP Over Time",
       subtitle = "2008 marks beginning of uncertain economy for Hungary",
       y = "GDP in USD") +
  scale_x_continuous(breaks = c(1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
pdf("graph2.pdf", width = 7, height = 5)
graph2
dev.off()
```

```{r}
graph3 <- stats %>% ggplot(aes(x = Year, y = Population)) +
  geom_line() +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = c(1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Population Over Time",
        subtitle = "Declining population a demographic crisis; likely a moderate contributor to social panic")
```

```{r}
pdf("graph3.pdf", width = 7, height = 5)
graph3
dev.off()
```

```{r}
graph4 <- stats %>% ggplot(aes(x = Year, y = Population)) +
  geom_line() +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = c(1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Population Over Time",
        subtitle = "Declining population a demographic crisis; likely a moderate contributor to social panic", caption = "Y axis origin forced to 0.") +
  expand_limits(y = 0)
```

```{r}
pdf("graph4.pdf", width = 7, height = 5)
graph4
dev.off()
```

```{r}
graph5 <- stats %>% ggplot(aes(x = Year, y = gdpPerCap)) +
  geom_line() +
  labs(title = "GDP Per Capita Over Time",
       subtitle = "Decline in population does not strongly affect GDP trend.",
       y = "GDP Per Capita in USD") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = c(1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
pdf("graph5.pdf", width = 7, height = 5)
graph5
dev.off()
```

```{r}
google2 <- read_xlsx("google2.xlsx")
```

```{r}
# graph6 <- google2 %>% ggplot(aes(x = Month)) +
#   geom_line(aes(y = OSFww, color = "'Open Society Foundations' Worldwide")) +
#   geom_line(aes(y = OSFus, color = "'Open Society Foundations' US")) +
#   geom_line(aes(y = OSFruWW, color = "Open Society Foundations (Russian) Russia")) +
#   geom_line(aes(y = OSUhuENG, color = "'Open Society Foundations' Hungary")) +
#   labs(title = "Google Trends for 'Soros' Search Terms Over Time",
#        caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time. All search terms in English unless denoted otherwise.",
#        y = "Relative Search Frequency",
#        x = "Time",
#        color = "Search Term")

# This is commented out because I'm not using this graph; it's really messy. But in case you want it, here it is.
```

```{r}
graph7 <- google2 %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = OSFww)) +
  labs(title = "Google Trends for 'Open Society Foundations' Search Term: Worldwide",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was 'Open Society Foundations' in English and worldwide.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph7.pdf", width = 10, height = 4)
graph7
dev.off()
```

```{r}
graph8 <- google2 %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = OSFus)) +
  labs(title = "Google Trends for 'Open Society Foundations' Search Term: US",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was 'Open Society Foundations' in English and in the US.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph8.pdf", width = 10, height = 4)
graph8
dev.off()
```

```{r}
# I'm pretty sure graphs 9 and 10 are the same, but I didn't delete on because I'm not entirely sure.

graph9 <- google2 %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = OSFruWW)) +
  labs(title = "Google Trends for Open Society Foundations (Russian) Search Term: Worldwide",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was 'Open Society Foundations' in Russian and worldwide.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph9.pdf", width = 10, height = 4)
graph9
dev.off()
```

```{r}
graph10 <- google2 %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = OSFruWW)) +
  labs(title = "Google Trends for Open Society Foundations (Russian) Search Term: Worldwide",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was 'Open Society Foundations' in Russian and worldwide.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph10.pdf", width = 10, height = 4)
graph10
dev.off()
```

```{r}
graph11 <- google2 %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = OSUhuENG)) +
  labs(title = "Google Trends for 'Open Society Foundations' Search Term: Hungary",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was 'Open Society Foundations' in English and in Hungary.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph11.pdf", width = 10, height = 4)
graph11
dev.off()
```

```{r}
google3 <- read_xlsx("google3.xlsx")
```

```{r}
graph12 <- google3 %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = CEUruWW)) +
  labs(title = "Google Trends for Central European University (Russian) Search Term: Worldwide",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was Central European University in Russian and worldwide.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph12.pdf", width = 10, height = 4)
graph12
dev.off()
```

```{r}
graph13 <- google3 %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = CEUruNDww)) +
  labs(title = "Google Trends for Central European University (Russian, No Dash) Search Term: Worldwide",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was 'Central European University' in Russian and worldwide.
       The original Russian term contains a dash that was omitted for this version.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph13.pdf", width = 10, height = 4)
graph13
dev.off()
```

```{r}
graph14 <- google3 %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = CEUhu)) +
  labs(title = "Google Trends for Central European University (Hungarian) Search Term: Hungary",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was Central European University in Hungarian and in Hungary.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph14.pdf", width = 10, height = 4)
graph14
dev.off()
```

```{r}
graph15 <- google3 %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = CEUhuNA)) +
  labs(title = "Google Trends for Central European University (Hungarian, No Diacritics) Search Term: Hungary",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was Central European University in Hungarian and in Hungary.
       The original Hungarian term contains diacritics that were omitted for this version.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph15.pdf", width = 10, height = 4)
graph15
dev.off()
```

```{r}
graph16 <- google3 %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = CEUhuENG)) +
  labs(title = "Google Trends for 'Central European University' Search Term: Hungary",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was Central European University in English and in Hungary.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph16.pdf", width = 10, height = 4)
graph16
dev.off()
```

```{r}
graph17 <- google3 %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = CEUus)) +
  labs(title = "Google Trends for 'Central European University' Search Term: US",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was Central European University in English and in the US.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph17.pdf", width = 10, height = 4)
graph17
dev.off()
```

```{r}
graph18 <- google3 %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = CEUww)) +
  labs(title = "Google Trends for 'Central European University' Search Term: Worldwide",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was Central European University in English and Worldwide.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph18.pdf", width = 10, height = 4)
graph18
dev.off()
```

```{r}
# The following four graphs are Graph 1 parsed out to be four individual graphs. They also reflect updated data that contains May 2020 (and relative adjustments thereto.)
```

```{r}
graph19 <- google %>% ggplot(aes(x = Month)) +
  geom_line(aes(y = sorosWW)) +
  labs(title = "Google Trends for 'Soros' Search Term: Worldwide",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was Soros in Latin letters and worldwide.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph19.pdf", width = 10, height = 4)
graph19
dev.off()
```

```{r}
graph20 <- google %>% ggplot(aes(x = Month)) +
    geom_line(aes(y = sorosCyrWW)) +
  labs(title = "Google Trends for Soros (Cyr.) Search Term: Worldwide",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was Soros in Cyrillic letters and worldwide.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph20.pdf", width = 10, height = 4)
graph20
dev.off()
```

```{r}
graph21 <- google %>% ggplot(aes(x = Month)) +
    geom_line(aes(y = sorosHU)) +
  labs(title = "Google Trends for 'Soros' Search Term: Hungary",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was Soros in Latin letters and in Hungary.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph21.pdf", width = 10, height = 4)
graph21
dev.off()
```

```{r}
graph22 <- google %>% ggplot(aes(x = Month)) +
      geom_line(aes(y = sorosUS)) +
  labs(title = "Google Trends for 'Soros' Search Term: US",
       caption = "Scale of 1-100 on Y axis determined by Google; numbers relative to each other over time.
       Search term was Soros in Latin letters and in the US.",
       y = "Relative Search Frequency",
       x = "Time")
```

```{r}
pdf("graph22.pdf", width = 10, height = 4)
graph22
dev.off()
```

```{r}
# Loading in data from Hungary Today. This is the R friendly version, so it should have no quotation marks or diacritics in the character cells.

htdirty <- read_xlsx("HTRfri.xlsx")

# The tics were coming from spaces in the column names. I also unfroze the top row and unbolded the font. I deleted the URL column as well. It still exists in the Google Sheets version of this dataset online.
```

```{r}
ht <- htdirty %>%
  mutate(Date = as_date(Date))

# for whatever reason, after messing around with the data some, it decided to randomly cast the Date columns as posixct. I converted it to Dates class here.

graph23 <- ht %>%
  ggplot(aes(x = Date, y = SorosMentions)) +
  geom_point() +
  geom_smooth(method = "loess") +
  geom_vline(colour="#DD1C1C", xintercept=as.numeric(ht$Date[c(189, 438)]))

graph23
```

```{r}
htmini <- ht %>%
  mutate(Year = year(Date)) %>%
  filter(Year == 2016)

graph24 <- htmini %>%
  ggplot(aes(x = Date)) +
  geom_point(aes(y = SorosMentions))

graph24
```

```{r}
htmini2 <- ht %>%
  mutate(Year = year(Date)) %>%
  filter(Year == 2017)

graph25 <- htmini2 %>%
  ggplot(aes(x = Date)) +
  geom_point(aes(y = SorosMentions))

graph25
```

```{r}
htmini3 <- ht %>%
  mutate(Year = year(Date)) %>%
  filter(Year == 2018)

graph26 <- htmini3 %>%
  ggplot(aes(x = Date)) +
  geom_point(aes(y = SorosMentions))

graph26
```

```{r}
htmini4 <- ht %>%
  mutate(Year = year(Date)) %>%
  filter(Year == 2019)

graph27 <- htmini4 %>%
  ggplot(aes(x = Date)) +
  geom_point(aes(y = SorosMentions))

graph27
```

```{r}
# Dist of SorosMentions

graph28 <- ht %>%
  ggplot(aes(x = SorosMentions)) +
  geom_histogram(bins = 20)

graph28
```

```{r}
graph29 <- ht %>%
  ggplot(aes(x = Date, y = SorosTag)) +
  geom_vline(colour="#DD1C1C", xintercept=ht$Date[c(189, 438)]) +
  # Please note the numbers above correspond to dates that special events occured, but not necessarily the actual news story I use to cite them in or the HT news story that discusses that event.
  geom_smooth(method = "loess")

graph29
```

```{r}
graph30 <- ht %>%
  ggplot(aes(x = Date, y = CEUMention)) +
  geom_point() +
  geom_vline(colour="#DD1C1C", xintercept=as.numeric(ht$Date[c(189, 438)])) +
  geom_smooth(method = "loess") +
  scale_y_continuous(expand = c(0, 0), limits = c(-1, 35))

graph30
```

```{r}
graph31 <- ht %>%
  ggplot(aes(x = Date, y = CEUTag)) +
  geom_vline(colour="#DD1C1C", xintercept=ht$Date[c(189, 438)]) +
  geom_smooth(method = "loess")

graph31
```

```{r}
graph32 <- ht %>%
  ggplot(aes(x = Date, y = Event)) +
  geom_smooth(method = "loess") +
  geom_vline(colour="#DD1C1C", xintercept=ht$Date[c(189, 438)])

graph32
```

```{r}
graph33 <- ht %>%
  ggplot(aes(x = Date, y = OSF)) +
  geom_smooth(method = "loess") +
  geom_vline(colour="#DD1C1C", xintercept=ht$Date[c(189, 438)])

graph33
```

```{r}
graph34 <- ht %>%
  ggplot(aes(x = Date, y = StopSoros)) +
  geom_smooth(method = "loess") +
  geom_vline(colour="#DD1C1C", xintercept=ht$Date[c(189, 438)])

graph34
```

```{r}
graph35 <- ht %>%
  ggplot(aes(x = Date, y = Elections)) +
  geom_smooth(method = "loess") +
  geom_vline(colour="#DD1C1C", xintercept=ht$Date[c(189, 438)])

graph35
```

```{r}
graph36 <- ht %>%
  ggplot(aes(x = Date, y = Event)) +
  geom_smooth(method = "loess") +
  geom_vline(colour="#DD1C1C", xintercept=ht$Date[c(189, 438)]) +
  geom_vline(colour="#1D8234", xintercept=ht$Date[c(40, 50, 92, 126, 151, 163, 208, 234, 289, 374, 391, 401, 422)])
# Please note the numbers above correspond to dates that special events occured, but not necessarily the actual news story I use to cite them in or the HT news story that discusses that event.
graph36
```

```{r}
graph37 <- ht %>%
  ggplot(aes(x = Date, y = SorosMentions)) +
  geom_point() +
  geom_smooth(method = "loess") +
  geom_vline(colour="#DD1C1C", xintercept=as.numeric(ht$Date[c(189, 438)])) +
  geom_vline(colour="#1D8234", xintercept=ht$Date[c(40, 50, 92, 126, 151, 163, 208, 234, 289, 374, 391, 401, 422)])

graph37
```

```{r}
# summing SorosMentions values by date

graph38 <- ht %>% 
  group_by(Date) %>% 
  summarise(Mentions = sum(SorosMentions)) %>%
  ggplot(aes(x = Date, y = Mentions)) +
  geom_point() +
  geom_smooth(method = "loess") +
  # I originally recalculated the line placement numbers to fit the grouped data, but I actually needed my original numbers weirdly enough.
  geom_vline(colour="#DD1C1C", xintercept=as.numeric(ht$Date[c(189, 428)]))
```

```{r}
# Reading in updated data from separate Excel file

htdirty2 <- read_xlsx("HTRfri2.xlsx")

ht2 <- htdirty2 %>%
  mutate(Date = as_date(Date))
```

```{r}
graph39 <- ht2 %>%
  ggplot(aes(x = Date, y = Terrorism)) +
  geom_point() +
  scale_y_continuous(expand = c(0, 0), limits = c(-0.1, 2)) +
  labs(title = "News Articles Mentioning Terrorism", subtitle = "Articles selected from Hungary Today", caption = "Point position at 1 denotes the article mentioned terrorism. Position at 0 denotes absence of the term.
       N = 453.", y = "Binary Presence/Absence of Term", x = "Article Publishing Date")
  

graph39
```

```{r}
pdf("graph39.pdf", width = 6, height = 4)
graph39
dev.off()
```

```{r}
graph40 <- ht2 %>%
  ggplot(aes(x = Date, y = Immigration)) +
  geom_point() +
  scale_y_continuous(expand = c(0, 0), limits = c(-0.1, 2)) +
  labs(title = "News Articles Mentioning Immigration", subtitle = "Articles selected from Hungary Today", caption = "Point position at 1 denotes the article mentioned immigration. Position at 0 denotes absence of the term.
  Curve fit to show trend in data.
       N = 453.", y = "Binary Presence/Absence of Term", x = "Article Publishing Date") +
  geom_smooth(method = "loess")
  

graph40
```

```{r}
pdf("graph40.pdf", width = 6, height = 4)
graph40
dev.off()
```

```{r}
graph41 <- ht2 %>%
  ggplot(aes(x = Date, y = Islamophobia)) +
  geom_point() +
  scale_y_continuous(expand = c(0, 0), limits = c(-0.1, 2)) +
  labs(title = "News Articles Mentioning Islamophobia", subtitle = "Articles selected from Hungary Today", caption = "Point position at 1 denotes the article mentioned Islamophobic statements.
  Position at 0 denotes absence of the term.
       N = 453.", y = "Binary Presence/Absence of Term", x = "Article Publishing Date")
  

graph41
```

```{r}
pdf("graph41.pdf", width = 6, height = 4)
graph41
dev.off()
```

```{r}
graph42 <- ht2 %>%
  ggplot(aes(x = Date, y = Christianity)) +
  geom_point() +
  scale_y_continuous(expand = c(0, 0), limits = c(-0.1, 2)) +
  labs(title = "News Articles Mentioning Christianity", subtitle = "Articles selected from Hungary Today", caption = "Point position at 1 denotes the article mentioned Christianity. Position at 0 denotes absence of the term.
       N = 453.", y = "Binary Presence/Absence of Term", x = "Article Publishing Date")
  

graph42
```

```{r}
pdf("graph42.pdf", width = 6, height = 4)
graph42
dev.off()
```

```{r}
# Reading in updated data that contains variables for mentions of the EU, the "Soros network," and both (EUSN).

htdirty3 <- read_xlsx("HTRfri3.xlsx")

ht3 <- htdirty3 %>%
  mutate(Date = as_date(Date))
```

```{r}
graph43 <- ht3 %>%
  ggplot(aes(x = Date, y = EUSN)) +
  geom_point() +
  scale_y_continuous(expand = c(0, 0), limits = c(-0.1, 2)) +
  labs(title = "News Articles Mentioning Both the EU and the Soros Network", subtitle = "Articles selected from Hungary Today", caption = "Point position at 1 denotes the article mentioned both terms.
  Position at 0 denotes absence of one or both of the terms.
       N = 453.", y = "Binary Presence/Absence of Terms", x = "Article Publishing Date") +
  geom_smooth(method = "loess")

graph43
```

```{r}
pdf("graph43.pdf", width = 6, height = 4)
graph43
dev.off()
```

